#pragma once

#include "gui/model.h"

namespace lanspeak::gui {

enum class TextId {
    file,
    capture_device,
    render_device,
    mic_gain,
    settings,
    language,
    language_auto,
    language_russian,
    language_english,
    start,
    stop,
    talk,
    talking,
    continuous_talk,
    add_contact,
    edit,
    delete_contact,
    default_capture_device,
    default_render_device,
    unnamed_contact,
    gain_short,
    duck_short,
    off,
    name,
    ip_host,
    port,
    contact_gain,
    self_ducking,
    threshold,
    attack_ms,
    hold_ms,
    release_ms,
    receive_buffer_ms,
    milliseconds_short,
    save,
    add,
    cancel,
    edit_contact_title,
    add_contact_title,
    name_required,
    host_required,
    port_required,
    save_settings_failed,
    device_refresh_failed,
    device_refresh_unusable,
    loaded_devices,
    already_running,
    listener_idle,
    add_contact_before_start,
    core_missing,
    create_pipe_failed,
    starting,
    create_process_failed,
    restarting,
    stopping,
    stopped,
    no_contacts_left,
    already_in_mode,
    listener_mode,
    duplex_mode,
    global_hotkeys,
    debug_console,
    audio_latency_diagnostics,
    device_name,
    audio_format,
    audio_engine_period,
    endpoint_buffer,
    maximum_stream_latency,
    current_render_padding,
    stream_mode,
    low_latency_shared_mode,
    standard_shared_mode,
    diagnostics_unavailable,
    diagnostics_not_available_short,
    channels_short,
    bits_short,
    latency_diagnostics_note,
    ptt_for_all,
    osd_me,
    contact_hotkeys,
    hotkey_not_set,
    hotkey_record,
    hotkey_recording,
    hotkey_clear,
    tray_show,
    tray_exit,
    include_in_global_ptt,
    exclude_from_global_ptt,
    help,
    about,
    about_product_version,
    about_author,
    about_github,
    ok
};

const wchar_t* localized_text(TextId id, LanguageSetting setting);

} // namespace lanspeak::gui
